services:
  - type: web
    name: t3e-interface
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: TURSO_DATABASE_URL
        sync: false
      - key: TURSO_AUTH_TOKEN
        sync: false
      - key: MDP_APP
        sync: false
      - key: NODE_ENV
        value: production
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: CONVERT_SERVICE_SECRET
        sync: false
      - key: SEAO_USERNAME
        sync: false
      - key: SEAO_PASSWORD
        sync: false
      - key: PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD
        value: "0"
